version: '3'
services:
  redis:
    image: redis

  db2:
    image: postgres:9.4

  vote:
    image: vaccinevoting-app
    ports:
      - 5004:80
    links:
      - redis

  worker:
    image: worker-app
    ports:
       - 5007:80
    links:
       - db2
       - redis

  result:
    image: result-app
    ports:
      - 5006:80
    links:
      - db2
